name: static analysis

on:
  workflow_call:
    inputs:
      idf_version:
        description: 'esp-idf SDK version'
        required: true
        type: string

jobs:
  static-analysis:
    name: Run clang tidy
    runs-on: ubuntu-20.04
    container: espressif/idf:${{inputs.idf_version}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install clang-check
        run: |
          . ${IDF_PATH}/export.sh
          idf_tools.py install esp-clang
      - name: run clang-check
        env:
          IDF_TOOLCHAIN: clang
        run: |
          . ${IDF_PATH}/export.sh
          idf.py clang-check