name: lint

on:
  workflow_call: {}

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🧹 Format Check
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'c,h,hpp,cpp'
          clangFormatVersion: 16
          style: file