name: Build target binary

on:
  workflow_call:
    inputs:
      idf_version:
        description: 'esp-idf SDK version'
        required: true
        type: string
      args:
        description: 'Arguments passed to the build command'
        default: ''
        required: false
        type: string
      working_dir:
        description: 'Path to the top-level directory of the target app'
        default: '.'
        required: false
        type: string

jobs:
  build:
    name: Build target
    runs-on: ubuntu-20.04
    container: espressif/idf:${{inputs.idf_version}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - run: |
          . ${IDF_PATH}/export.sh
          cd ${{working_dir}}
          idf.py build ${{inputs.args}}